### ISSUE TITLE
Blogpost: Fakir

### ISSUE THREAD

**Issue by amrrs** [ThinkR-open/fakir#1]
Hello,

I had just put together a small blogpost on this, thought to share with you https://www.programmingwithr.com/how-to-generate-meaningful-fake-data-for-learning-experimentation-and-teaching/ 

Thanks,
Abdul

<Close it when you had seen this post>

**Comment by ColinFay** [comment]
Thanks a lot @amrrs !!

**Comment by amrrs** [comment]
@ColinFay  My pleasure!
